## Redis server properties
#spring.redis.host=localhost
#spring.redis.port=6379

spring:
  application:
    name: sale_dynamics
  datasource:
    url: jdbc:mysql://localhost:3306/sale_dynamics
    username: root
    password: root123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true