## Redis server properties
#spring.redis.host=localhost
#spring.redis.port=6379

spring:
  application:
    name: sale_dynamics
  datasource:
    url: jdbc:mysql://localhost:3306/final_pos
    username: root
    password: root123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
mail:
  host: smtp.gmail.com
  port: 465
  username: excorp1123@gmail.com
  password: D^lphin123
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true