## Redis server properties
#spring.redis.host=localhost
#spring.redis.port=6379

spring:
  application:
    name: sale_dynamics
  datasource:
    url: ${MYSQL_HOST_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true